// Generated by gencpp from file cob_3d_mapping_msgs/GetGeometryMap.msg
// DO NOT EDIT!


#ifndef COB_3D_MAPPING_MSGS_MESSAGE_GETGEOMETRYMAP_H
#define COB_3D_MAPPING_MSGS_MESSAGE_GETGEOMETRYMAP_H

#include <ros/service_traits.h>


#include <cob_3d_mapping_msgs/GetGeometryMapRequest.h>
#include <cob_3d_mapping_msgs/GetGeometryMapResponse.h>


namespace cob_3d_mapping_msgs
{

struct GetGeometryMap
{

typedef GetGeometryMapRequest Request;
typedef GetGeometryMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGeometryMap
} // namespace cob_3d_mapping_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMap > {
  static const char* value()
  {
    return "f00740a6f429ef52cd72626c52eeda1c";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMap&) { return value(); }
};

template<>
struct DataType< ::cob_3d_mapping_msgs::GetGeometryMap > {
  static const char* value()
  {
    return "cob_3d_mapping_msgs/GetGeometryMap";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMap&) { return value(); }
};


// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMapRequest> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMap > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMap >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetGeometryMapRequest> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetGeometryMap > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetGeometryMapRequest>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetGeometryMap >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMapResponse> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMap > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetGeometryMap >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetGeometryMapResponse> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetGeometryMap > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetGeometryMapResponse>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetGeometryMap >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetGeometryMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_3D_MAPPING_MSGS_MESSAGE_GETGEOMETRYMAP_H
