// Generated by gencpp from file cob_3d_mapping_msgs/GetObjectsOfClass.msg
// DO NOT EDIT!


#ifndef COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASS_H
#define COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASS_H

#include <ros/service_traits.h>


#include <cob_3d_mapping_msgs/GetObjectsOfClassRequest.h>
#include <cob_3d_mapping_msgs/GetObjectsOfClassResponse.h>


namespace cob_3d_mapping_msgs
{

struct GetObjectsOfClass
{

typedef GetObjectsOfClassRequest Request;
typedef GetObjectsOfClassResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectsOfClass
} // namespace cob_3d_mapping_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClass > {
  static const char* value()
  {
    return "bb62786e2e510337925d5e129d0dd7cb";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClass&) { return value(); }
};

template<>
struct DataType< ::cob_3d_mapping_msgs::GetObjectsOfClass > {
  static const char* value()
  {
    return "cob_3d_mapping_msgs/GetObjectsOfClass";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClass&) { return value(); }
};


// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClass > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClass >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetObjectsOfClass > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetObjectsOfClassRequest>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetObjectsOfClass >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClassResponse> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClass > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClassResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetObjectsOfClass >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetObjectsOfClassResponse> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetObjectsOfClass > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetObjectsOfClassResponse>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetObjectsOfClass >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetObjectsOfClassResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_3D_MAPPING_MSGS_MESSAGE_GETOBJECTSOFCLASS_H
