// Generated by gencpp from file cob_3d_mapping_msgs/GetPlane.msg
// DO NOT EDIT!


#ifndef COB_3D_MAPPING_MSGS_MESSAGE_GETPLANE_H
#define COB_3D_MAPPING_MSGS_MESSAGE_GETPLANE_H

#include <ros/service_traits.h>


#include <cob_3d_mapping_msgs/GetPlaneRequest.h>
#include <cob_3d_mapping_msgs/GetPlaneResponse.h>


namespace cob_3d_mapping_msgs
{

struct GetPlane
{

typedef GetPlaneRequest Request;
typedef GetPlaneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlane
} // namespace cob_3d_mapping_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetPlane > {
  static const char* value()
  {
    return "e11c006bc7fabf06881bc7d0de7ba820";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetPlane&) { return value(); }
};

template<>
struct DataType< ::cob_3d_mapping_msgs::GetPlane > {
  static const char* value()
  {
    return "cob_3d_mapping_msgs/GetPlane";
  }

  static const char* value(const ::cob_3d_mapping_msgs::GetPlane&) { return value(); }
};


// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetPlaneRequest> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetPlane > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetPlaneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetPlane >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetPlaneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetPlaneRequest> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetPlane > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetPlaneRequest>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetPlane >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetPlaneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetPlaneResponse> should match 
// service_traits::MD5Sum< ::cob_3d_mapping_msgs::GetPlane > 
template<>
struct MD5Sum< ::cob_3d_mapping_msgs::GetPlaneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_3d_mapping_msgs::GetPlane >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetPlaneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_3d_mapping_msgs::GetPlaneResponse> should match 
// service_traits::DataType< ::cob_3d_mapping_msgs::GetPlane > 
template<>
struct DataType< ::cob_3d_mapping_msgs::GetPlaneResponse>
{
  static const char* value()
  {
    return DataType< ::cob_3d_mapping_msgs::GetPlane >::value();
  }
  static const char* value(const ::cob_3d_mapping_msgs::GetPlaneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_3D_MAPPING_MSGS_MESSAGE_GETPLANE_H
