; Auto-generated. Do not edit!


(cl:in-package cob_3d_mapping_msgs-msg)


;//! \htmlinclude PlaneExtractionGoal.msg.html

(cl:defclass <PlaneExtractionGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlaneExtractionGoal (<PlaneExtractionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaneExtractionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaneExtractionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_3d_mapping_msgs-msg:<PlaneExtractionGoal> is deprecated: use cob_3d_mapping_msgs-msg:PlaneExtractionGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaneExtractionGoal>) ostream)
  "Serializes a message object of type '<PlaneExtractionGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaneExtractionGoal>) istream)
  "Deserializes a message object of type '<PlaneExtractionGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaneExtractionGoal>)))
  "Returns string type for a message object of type '<PlaneExtractionGoal>"
  "cob_3d_mapping_msgs/PlaneExtractionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaneExtractionGoal)))
  "Returns string type for a message object of type 'PlaneExtractionGoal"
  "cob_3d_mapping_msgs/PlaneExtractionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaneExtractionGoal>)))
  "Returns md5sum for a message object of type '<PlaneExtractionGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaneExtractionGoal)))
  "Returns md5sum for a message object of type 'PlaneExtractionGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaneExtractionGoal>)))
  "Returns full string definition for message of type '<PlaneExtractionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Trigger Plane Extraction~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaneExtractionGoal)))
  "Returns full string definition for message of type 'PlaneExtractionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Trigger Plane Extraction~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaneExtractionGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaneExtractionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaneExtractionGoal
))
