; Auto-generated. Do not edit!


(cl:in-package cob_3d_mapping_msgs-msg)


;//! \htmlinclude TriggerResult.msg.html

(cl:defclass <TriggerResult> (roslisp-msg-protocol:ros-message)
  ((message
    :reader message
    :initarg :message
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass TriggerResult (<TriggerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TriggerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TriggerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_3d_mapping_msgs-msg:<TriggerResult> is deprecated: use cob_3d_mapping_msgs-msg:TriggerResult instead.")))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <TriggerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_3d_mapping_msgs-msg:message-val is deprecated.  Use cob_3d_mapping_msgs-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TriggerResult>) ostream)
  "Serializes a message object of type '<TriggerResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'message) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TriggerResult>) istream)
  "Deserializes a message object of type '<TriggerResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'message) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TriggerResult>)))
  "Returns string type for a message object of type '<TriggerResult>"
  "cob_3d_mapping_msgs/TriggerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TriggerResult)))
  "Returns string type for a message object of type 'TriggerResult"
  "cob_3d_mapping_msgs/TriggerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TriggerResult>)))
  "Returns md5sum for a message object of type '<TriggerResult>"
  "d8c2dd3109bf1dc2423499244e4009cf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TriggerResult)))
  "Returns md5sum for a message object of type 'TriggerResult"
  "d8c2dd3109bf1dc2423499244e4009cf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TriggerResult>)))
  "Returns full string definition for message of type '<TriggerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/String message~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TriggerResult)))
  "Returns full string definition for message of type 'TriggerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/String message~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TriggerResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TriggerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TriggerResult
    (cl:cons ':message (message msg))
))
