version: '2'
services:
  master:
    image: ros:kinetic
    container_name: master
    command:
      - roscore

  astra:
    build: './astra_docker'
    container_name: astra
    environment:
      - "ROS_HOSTNAME=astra"
      - "ROS_MASTER_URI=http://master:11311"
    devices:
      - "/dev/bus/usb/001/016"
    command: roslaunch astra_launch astra.launch

  cob_people_object_detection:
    build: './cob_people_object_detection'
    container_name: cob_people_object_detection
    environment:
      - "ROS_HOSTNAME=cob_people_object_detection"
      - "ROS_MASTER_URI=http://master:11311"
    command: /bin/bash -c 'source /root/catkin_ws/devel/setup.bash && roslaunch cob_people_object_detection_tensorflow alltogether.launch'

  listener:
    image: ros:kinetic
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: rostopic hz /camera/depth/image_raw
 
