#	@file
#	@section COPYRIGHT
#	Copyright (C) 2019 Consequential Robotics (CqR)
#	
#	@section AUTHOR
#	Consequential Robotics http://consequentialrobotics.com
#	
#	@section LICENSE
#	For a full copy of the license agreement, see LICENSE.MDK in
#	the MDK root directory.
#	
#	Subject to the terms of this Agreement, Consequential Robotics
#	grants to you a limited, non-exclusive, non-transferable license,
#	without right to sub-license, to use MIRO Developer Kit in
#	accordance with this Agreement and any other written agreement
#	with Consequential Robotics. Consequential Robotics does not
#	transfer the title of MIRO Developer Kit to you; the license
#	granted to you is not a sale. This agreement is a binding legal
#	agreement between Consequential Robotics and the purchasers or
#	users of MIRO Developer Kit.
#	
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#	NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#	WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
#	OTHER DEALINGS IN THE SOFTWARE.
#	
#	@section DESCRIPTION
#

def __DEG2RAD(x):
    return x * 0.017453292519943

def __BIT(x):
    return 1<<x

MIRO_DOF_MAXIMUM_SPEED = 253
MIRO_DOF_ENABLE_POS_DEADZONE = 254
MIRO_DOF_DISABLE_POS_DEADZONE = 255
MIRO_DOF_USE_INI = 42.0
MIRO_DOF_GO_INACTIVE = 43.0
MIRO_WHEEL_DIAM_MM = 90.0
MIRO_WHEEL_TRACK_MM = 164.0
MIRO_WHEEL_MAX_SPEED_MMPERSEC = 400.0
MIRO_WHEEL_COUNTS_PER_MOTOR_ROT = 4
MIRO_WHEEL_GEARBOX_RATIO = 39.822
MIRO_WHEEL_CMD_SPEED_PER_MMPERSEC = 0.21
MIRO_TILT_COUNTS_AT_ZERO_RAD = (100.0)
MIRO_TILT_COUNTS_PER_RAD = (100.0)
MIRO_TILT_MIN_RAD = __DEG2RAD(   -5.0)
MIRO_TILT_MAX_RAD = __DEG2RAD(   -5.0)
MIRO_TILT_INI_RAD = MIRO_TILT_MIN_RAD
MIRO_TILT_MIN_COUNTS = 50
MIRO_TILT_MAX_COUNTS = 150
MIRO_TILT_CALIB_COUNTS = 100
MIRO_TILT_SPEED_COUNTS = MIRO_DOF_MAXIMUM_SPEED
MIRO_LIFT_COUNTS_AT_ZERO_RAD = (272.0)
MIRO_LIFT_COUNTS_PER_RAD = (-183.3465)
MIRO_LIFT_MIN_RAD = __DEG2RAD(   17.0) 
MIRO_LIFT_MAX_RAD = __DEG2RAD(   65.0) 
MIRO_LIFT_INI_RAD = MIRO_LIFT_MIN_RAD 
MIRO_LIFT_MIN_COUNTS = 0
MIRO_LIFT_MAX_COUNTS = 255
MIRO_LIFT_CALIB_COUNTS = 128
MIRO_LIFT_SPEED_COUNTS = MIRO_DOF_MAXIMUM_SPEED
MIRO_LIFT_UPRIGHT = ((MIRO_LIFT_MIN_RAD * MIRO_LIFT_COUNTS_PER_RAD + MIRO_LIFT_COUNTS_AT_ZERO_RAD))
MIRO_LIFT_SHELL_RELEASE = ((MIRO_LIFT_MAX_RAD * MIRO_LIFT_COUNTS_PER_RAD + MIRO_LIFT_COUNTS_AT_ZERO_RAD))
MIRO_PITCH_COUNTS_AT_ZERO_RAD = (107.000) 
MIRO_PITCH_COUNTS_PER_RAD = (-204.086) 
MIRO_PITCH_MIN_RAD = __DEG2RAD(  -15.0) 
MIRO_PITCH_MAX_RAD = __DEG2RAD(    8.0) 
MIRO_PITCH_INI_RAD = -(MIRO_TILT_INI_RAD+MIRO_LIFT_INI_RAD) 
MIRO_PITCH_MIN_COUNTS = 0
MIRO_PITCH_MAX_COUNTS = 255
MIRO_PITCH_CALIB_COUNTS = (MIRO_PITCH_COUNTS_AT_ZERO_RAD)
MIRO_PITCH_SPEED_COUNTS = MIRO_DOF_MAXIMUM_SPEED
MIRO_YAW_COUNTS_AT_ZERO_RAD = (128.0)     
MIRO_YAW_COUNTS_PER_RAD = (64.0 / __DEG2RAD(45.0)) 
MIRO_YAW_MIN_RAD = __DEG2RAD(   -60.0) 
MIRO_YAW_MAX_RAD = __DEG2RAD(    60.0) 
MIRO_YAW_INI_RAD = __DEG2RAD(     0.0)
MIRO_YAW_MIN_COUNTS = 0
MIRO_YAW_MAX_COUNTS = 255
MIRO_YAW_CALIB_COUNTS = (MIRO_YAW_COUNTS_AT_ZERO_RAD)
MIRO_YAW_SPEED_COUNTS = (MIRO_DOF_MAXIMUM_SPEED / 6)
MIRO_BODY_MOVE_START = __BIT(0)
MIRO_BODY_MOVE_CONTINUE = __BIT(1)
MIRO_BODY_MOVE_ABSOLUTE = __BIT(2)
MIRO_BODY_PUSH_IMPULSE = __BIT(0)
MIRO_BODY_PUSH_VELOCITY = __BIT(1)
MIRO_BODY_PUSH_ZERO_POSE_DR = __BIT(2)
MIRO_LINK_WORLD = -1
MIRO_LINK_FOOT = 0
MIRO_LINK_BODY = 1
MIRO_LINK_NECK = 2
MIRO_LINK_GIMBAL = 3
MIRO_LINK_HEAD = 4
MIRO_LINK_COUNT = 5
MIRO_JOINT_TILT = 0
MIRO_JOINT_LIFT = 1
MIRO_JOINT_YAW = 2
MIRO_JOINT_PITCH = 3
MIRO_JOINT_COUNT = 4
MIRO_P2_ACTION_MULL = 0
MIRO_P2_ACTION_HALT = 1
MIRO_P2_ACTION_ORIENT = 2
MIRO_P2_ACTION_APPROACH = 3
MIRO_P2_ACTION_FLEE = 4
MIRO_P2_ACTION_RETREAT = 5
MIRO_P2_ACTION_NUM_IMP = 6
MIRO_P2_ACTION_NUM_MAX = 8 
MIRO_P2_ACTION_NONE = 0xFFFFFFFF
MIRO_P2B_W_BRANCH_ENABLE = __BIT( 0)
MIRO_P2B_W_BRANCH_NO_SELECTION = __BIT( 1)
MIRO_P2S_W_SPATIAL_ENABLE = __BIT( 0)
MIRO_P2S_W_SPATIAL_IGNORE_AUDIO = __BIT( 1)
MIRO_P2S_W_SPATIAL_IGNORE_VIDEO = __BIT( 2)
MIRO_P2S_W_SPATIAL_SEND_PRIORITY = __BIT( 3	)
MIRO_P2S_W_SPATIAL_SEND_OTHER = __BIT( 4)
MIRO_P2S_W_SPATIAL_NO_REAFF_COMPROMISE = __BIT( 5)
MIRO_P2S_W_SPATIAL_NO_SUPPRESS = __BIT( 6)
MIRO_P2S_W_SPATIAL_SHOW_COMPROMISE = __BIT( 7)
MIRO_P2S_W_SPATIAL_SHOW_TEST_PATTERN = __BIT( 8)
MIRO_P2U_W_AFFECT_ENABLE = __BIT( 0)
MIRO_P2U_W_AFFECT_ADJUST_RTC = __BIT( 1)
MIRO_P2U_W_AFFECT_VALENCE_DYNAMICS = __BIT( 2)
MIRO_P2U_W_AFFECT_AROUSAL_DYNAMICS = __BIT( 3)
MIRO_P2U_W_AFFECT_NO_NEGATIVE_VALENCE = __BIT( 4)
MIRO_P2U_W_AFFECT_ENABLE_SLEEP = __BIT( 8	)
MIRO_P2U_W_AFFECT_FROM_CLOCK = __BIT( 12)
MIRO_P2U_W_AFFECT_FROM_WAKEFULNESS = __BIT( 13)
MIRO_P2U_W_AFFECT_FROM_LIGHT = __BIT( 14)
MIRO_P2U_W_AFFECT_FROM_TOUCH = __BIT( 16)
MIRO_P2U_W_AFFECT_FROM_SOUND = __BIT( 17)
MIRO_P2U_W_AFFECT_FROM_ACCEL = __BIT( 18)
MIRO_P2U_W_AFFECT_FROM_SLEEP_BLOCKED = __BIT( 19)
MIRO_P2U_W_AFFECT_RANDOMIZE_VALENCE = __BIT( 24	)
MIRO_P2U_W_AFFECT_FAST_SLEEP_DYNAMICS = __BIT( 25	)
MIRO_P2U_W_EXPRESS_ENABLE = __BIT( 0)
MIRO_P2U_W_EXPRESS_THROUGH_LIGHT = __BIT( 8)
MIRO_P2U_W_EXPRESS_THROUGH_VOCAL = __BIT( 9)
MIRO_P2U_W_EXPRESS_THROUGH_TAIL = __BIT( 10)
MIRO_P2U_W_EXPRESS_THROUGH_EYELIDS = __BIT( 11)
MIRO_P2U_W_EXPRESS_THROUGH_EARS = __BIT( 12)
MIRO_P2U_W_EXPRESS_THROUGH_BODY = __BIT( 13)
MIRO_P2U_W_EXPRESS_DEBUG_SONAR = __BIT( 14)
MIRO_P2U_W_EXPRESS_NO_PIRATE_NOISES = __BIT( 24	)
MIRO_P2U_W_EXPRESS_DO_PIRATE_NOISES = __BIT( 25	)
MIRO_P2U_W_ACTION_ENABLE = __BIT( 0)
MIRO_P2U_W_ACTION_DEBUG = __BIT( 1)
MIRO_P2U_W_ACTION_FORCE_MULL = __BIT( 2)
MIRO_P2U_W_ACTION_RANDOMIZE_ORIENT = __BIT( 3	)
MIRO_P2U_W_ACTION_DISABLE_HALT = __BIT( 4)
MIRO_P2U_W_ACTION_MODULATE_BY_SONAR = __BIT( 5)
MIRO_P2U_W_ACTION_DISABLE_RETREAT = __BIT( 6)
MIRO_P2U_W_ACTION_SHUN_CLIFFS = __BIT( 7)
MIRO_P2U_W_ACTION_SHUN_CLIFFS_DEBUG = __BIT( 8)
MIRO_P2U_W_ACTION_DISABLE_FLEE = __BIT( 9)
MIRO_P2U_W_BODY_ENABLE = __BIT( 0)
MIRO_P2U_W_BODY_RESET_KC_INTEGRATORS = __BIT( 1)
MIRO_P2U_W_BODY_NO_PUSH = __BIT( 8	)
MIRO_P2U_W_BODY_NO_PUSH_MOTION = __BIT( 9	)
MIRO_P2U_W_BODY_NO_PUSH_TRANSLATION = __BIT( 10	)
MIRO_P2U_W_BODY_NO_PUSH_INTO_SONAR = __BIT( 11	)
MIRO_P2U_W_LEAN_SPEED_INF = -1.0
MIRO_P2L_W_NO_ASCENDING = __BIT( 0)
MIRO_P2L_W_NO_DESCENDING = __BIT( 1)
MIRO_P2L_W_NO_AUTOFLAG = __BIT( 2)
MIRO_P2L_W_NO_DRIVE_BODY_VEL = __BIT( 4)
MIRO_P2L_W_ZERO_DRIVE_BODY_VEL = __BIT( 5)
MIRO_P2L_W_NO_DRIVE_EYELIDS = __BIT( 6)
MIRO_P2L_W_ZERO_DRIVE_EYELIDS = __BIT( 7)
MIRO_P2L_W_NO_DRIVE_EARS = __BIT( 8)
MIRO_P2L_W_ZERO_DRIVE_EARS = __BIT( 9)
MIRO_P2L_W_NO_DRIVE_TAIL = __BIT( 10)
MIRO_P2L_W_ZERO_DRIVE_TAIL = __BIT( 11)
MIRO_P2L_W_NO_DRIVE_LIGHTS = __BIT( 12)
MIRO_P2L_W_ENABLE_POS_CONTROL = __BIT( 13	)
MIRO_P2L_W_ENABLE_CLIFF_REFLEX = __BIT( 14	)
MIRO_P2L_W_FLIP_DRIVE_LEFT_EAR = __BIT( 15)
MIRO_P2L_W_FLIP_DRIVE_RIGHT_EAR = __BIT( 16)
MIRO_P2L_W_DESTALL_EARS_NOW = __BIT( 17)
MIRO_P2L_W_CLEAR_STREAM_BUFS = __BIT( 20)
MIRO_P2L_W_TRIGGER_RECORD_NAME = __BIT( 21)
MIRO_P2L_W_DEBUG_STREAMING = __BIT( 24)
MIRO_P2L_W_DEBUG_BUZZING = __BIT( 25)
MIRO_P2L_W_DEBUG_COMPROMISE = __BIT( 26)
MIRO_P1_W_NO_I2C = __BIT( 0 )
MIRO_P1_W_NO_SYSTEM = __BIT( 1 )
MIRO_P1_W_NO_ASCENDING = __BIT( 2 )
MIRO_P1_W_NO_LOOPS = __BIT( 3 )
MIRO_P1_W_NO_CONTROLLER = __BIT( 4 )
MIRO_P1_W_NO_DESCENDING = __BIT( 5 )
MIRO_P1_W_NO_POSCONT = __BIT( 6 )
MIRO_P1_W_NO_BODY_SYNERGY = __BIT( 7 )
MIRO_P1_W_NO_ACCEL_LIMIT = __BIT( 8 )
MIRO_P1_W_NO_CLIFF_REFLEX = __BIT( 9 )
MIRO_P1_W_NO_STALL_DETECT = __BIT( 10)
MIRO_P1_W_NO_STALL_ON_UC4 = __BIT( 11)
MIRO_P1_W_NO_AUTO_DESTALL = __BIT( 12)
MIRO_P1_W_TRIGGER_DESTALL = __BIT( 13 )
MIRO_P1_W_NO_FREEZE_ON_ACCEL = __BIT( 14 )
MIRO_P1_W_NO_FREEZE_ON_TOUCH = __BIT( 15 )
MIRO_P1_W_FREEZE_ON_LIGHT = __BIT( 16 )
MIRO_P1_W_TRIGGER_FREEZE = __BIT( 17 )
MIRO_P1_W_LED1_ON = __BIT( 18 )
MIRO_P1_W_LED2_ON = __BIT( 19 )
MIRO_P1_W_NO_RETREAT_ON_STALL = __BIT( 20)
MIRO_P1_W_NO_RETREAT_ON_CLIFF = __BIT( 21)
MIRO_P1_W_NO_RETREAT_ON_TIMER = __BIT( 22)
MIRO_P1_W_NO_DPG = __BIT( 23)
MIRO_P1_W_RESET_MODEL = __BIT( 24)
MIRO_P1_W_RESET_POSCONT = __BIT( 25 )
MIRO_P1_W_LOW_POWER_MODE = __BIT( 26)
MIRO_P1_W_RESET_ADPCM = __BIT( 27)
MIRO_P1_W_SEND_LOG = __BIT( 28)
MIRO_P1_W_NO_I2C_BUSY_ALARM = __BIT( 29)
MIRO_P1_W_SET_DEV_MODE = __BIT( 30)
MIRO_P1_W_TEST_ALARM = __BIT( 31 )
MIRO_BRIDGE_UPDATE = __BIT(0)
MIRO_BRIDGE_NO_PUBLISH_MICS = __BIT(1)
MIRO_BRIDGE_NO_PUBLISH_CAMS = __BIT(2)
