# generated from genmsg/cmake/pkg-msg-paths.cmake.develspace.in

set(cob_object_detection_msgs_MSG_INCLUDE_DIRS "/home/filippo/catkin_workspace_SOFAR_semantic_slam/devel/share/cob_object_detection_msgs/msg;/home/filippo/catkin_workspace_SOFAR_semantic_slam/src/module3/cob_perception_common/cob_object_detection_msgs/msg")
set(cob_object_detection_msgs_MSG_DEPENDENCIES actionlib_msgs;geometry_msgs;sensor_msgs;std_msgs;std_srvs)
