; Auto-generated. Do not edit!


(cl:in-package cob_object_detection_msgs-msg)


;//! \htmlinclude TrainObjectGoal.msg.html

(cl:defclass <TrainObjectGoal> (roslisp-msg-protocol:ros-message)
  ((object_name
    :reader object_name
    :initarg :object_name
    :type cl:string
    :initform ""))
)

(cl:defclass TrainObjectGoal (<TrainObjectGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrainObjectGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrainObjectGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_object_detection_msgs-msg:<TrainObjectGoal> is deprecated: use cob_object_detection_msgs-msg:TrainObjectGoal instead.")))

(cl:ensure-generic-function 'object_name-val :lambda-list '(m))
(cl:defmethod object_name-val ((m <TrainObjectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_object_detection_msgs-msg:object_name-val is deprecated.  Use cob_object_detection_msgs-msg:object_name instead.")
  (object_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrainObjectGoal>) ostream)
  "Serializes a message object of type '<TrainObjectGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'object_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'object_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrainObjectGoal>) istream)
  "Deserializes a message object of type '<TrainObjectGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'object_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrainObjectGoal>)))
  "Returns string type for a message object of type '<TrainObjectGoal>"
  "cob_object_detection_msgs/TrainObjectGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrainObjectGoal)))
  "Returns string type for a message object of type 'TrainObjectGoal"
  "cob_object_detection_msgs/TrainObjectGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrainObjectGoal>)))
  "Returns md5sum for a message object of type '<TrainObjectGoal>"
  "2f12226348d323c2e5b2031b3da53f1b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrainObjectGoal)))
  "Returns md5sum for a message object of type 'TrainObjectGoal"
  "2f12226348d323c2e5b2031b3da53f1b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrainObjectGoal>)))
  "Returns full string definition for message of type '<TrainObjectGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The goal~%string object_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrainObjectGoal)))
  "Returns full string definition for message of type 'TrainObjectGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The goal~%string object_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrainObjectGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'object_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrainObjectGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TrainObjectGoal
    (cl:cons ':object_name (object_name msg))
))
