// Generated by gencpp from file miro_msgs/priority_peak.msg
// DO NOT EDIT!


#ifndef MIRO_MSGS_MESSAGE_PRIORITY_PEAK_H
#define MIRO_MSGS_MESSAGE_PRIORITY_PEAK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace miro_msgs
{
template <class ContainerAllocator>
struct priority_peak_
{
  typedef priority_peak_<ContainerAllocator> Type;

  priority_peak_()
    : azim(0.0)
    , elev(0.0)
    , height(0.0)
    , size(0.0)
    , t_complete(0)  {
    }
  priority_peak_(const ContainerAllocator& _alloc)
    : azim(0.0)
    , elev(0.0)
    , height(0.0)
    , size(0.0)
    , t_complete(0)  {
  (void)_alloc;
    }



   typedef float _azim_type;
  _azim_type azim;

   typedef float _elev_type;
  _elev_type elev;

   typedef float _height_type;
  _height_type height;

   typedef float _size_type;
  _size_type size;

   typedef int32_t _t_complete_type;
  _t_complete_type t_complete;




  typedef boost::shared_ptr< ::miro_msgs::priority_peak_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::miro_msgs::priority_peak_<ContainerAllocator> const> ConstPtr;

}; // struct priority_peak_

typedef ::miro_msgs::priority_peak_<std::allocator<void> > priority_peak;

typedef boost::shared_ptr< ::miro_msgs::priority_peak > priority_peakPtr;
typedef boost::shared_ptr< ::miro_msgs::priority_peak const> priority_peakConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::miro_msgs::priority_peak_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::miro_msgs::priority_peak_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace miro_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/msg'], 'miro_msgs': ['/mnt/data/Dropbox/CqR/MIRO1/miro1/mdk/share/miro_msgs/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::miro_msgs::priority_peak_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::miro_msgs::priority_peak_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::miro_msgs::priority_peak_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::miro_msgs::priority_peak_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::miro_msgs::priority_peak_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::miro_msgs::priority_peak_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::miro_msgs::priority_peak_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5c53b287ed91e19422f1ad6f4de41f1";
  }

  static const char* value(const ::miro_msgs::priority_peak_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5c53b287ed91e19ULL;
  static const uint64_t static_value2 = 0x422f1ad6f4de41f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::miro_msgs::priority_peak_<ContainerAllocator> >
{
  static const char* value()
  {
    return "miro_msgs/priority_peak";
  }

  static const char* value(const ::miro_msgs::priority_peak_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::miro_msgs::priority_peak_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 azim\n\
float32 elev\n\
float32 height\n\
float32 size\n\
int32 t_complete\n\
\n\
";
  }

  static const char* value(const ::miro_msgs::priority_peak_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::miro_msgs::priority_peak_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.azim);
      stream.next(m.elev);
      stream.next(m.height);
      stream.next(m.size);
      stream.next(m.t_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct priority_peak_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::miro_msgs::priority_peak_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::miro_msgs::priority_peak_<ContainerAllocator>& v)
  {
    s << indent << "azim: ";
    Printer<float>::stream(s, indent + "  ", v.azim);
    s << indent << "elev: ";
    Printer<float>::stream(s, indent + "  ", v.elev);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "size: ";
    Printer<float>::stream(s, indent + "  ", v.size);
    s << indent << "t_complete: ";
    Printer<int32_t>::stream(s, indent + "  ", v.t_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRO_MSGS_MESSAGE_PRIORITY_PEAK_H
