(cl:in-package cob_object_detection_msgs-srv)
(cl:export '(NUMBER_POINTS-VAL
          NUMBER_POINTS
          FRAME_VIEW_NUMBER-VAL
          FRAME_VIEW_NUMBER
          CONE_POINTS_PER_PLANE-VAL
          CONE_POINTS_PER_PLANE
          LIMIT_ERROR_MATCHING-VAL
          LIMIT_ERROR_MATCHING
          BA_KERNEL_PARAM-VAL
          BA_KERNEL_PARAM
          BA_NUM_ITER-VAL
          BA_NUM_ITER
          BA_INITIAL_MU-VAL
          BA_INITIAL_MU
          BA_FINAL_MU_FACTOR-VAL
          BA_FINAL_MU_FACTOR
          BA_TAU-VAL
          BA_TAU
          ANGLE_SIGMA_DEGREE-VAL
          ANGLE_SIGMA_DEGREE
          TRANSLATE_SIGMA_M-VAL
          TRANSLATE_SIGMA_M
          OBS_POINT_SIGMA_M-VAL
          OBS_POINT_SIGMA_M
          WORLD_POINT_SIGMA_M-VAL
          WORLD_POINT_SIGMA_M
          MEAN_ERROR-VAL
          MEAN_ERROR
          STD_DEV-VAL
          STD_DEV
          MIN_ERROR-VAL
          MIN_ERROR
          MAX_ERROR-VAL
          MAX_ERROR
          RUNS_COUNT-VAL
          RUNS_COUNT
          RUNS_SUM-VAL
          RUNS_SUM
          RUNS_SUM2-VAL
          RUNS_SUM2
          TIME_DURATION-VAL
          TIME_DURATION
          OBSERVATIONS-VAL
          OBSERVATIONS
          FALSE_MATCHINGS-VAL
          FALSE_MATCHINGS
          RESULT-VAL
          RESULT
))